name: CI/CD Pipeline with Security Testing

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install bandit pytest

    - name: Run Bandit (SAST)
      run: bandit -r .

    - name: Run tests
      run: pytest test_example.py

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Staging
      run: echo "Deploying application to staging environment..."
